BUG: Fix data paths in preprocessing episode solutions notebook
Fix data paths in preprocessing episode solutions notebook.

Fixes:
```
 ----> 3 layout = BIDSLayout("../../data/ds000221", validate=False)
ValueError: BIDS root does not exist: /home/runner/work/SDC-BIDS-dMRI/SDC-BIDS-dMRI/code/data/ds000221
```

reported in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/runs/3251572017?check_suite_focus=true#step:13:120