BUG: Fix FSL `eddy` command call
Fix FSL `eddy` command call: `eddy_openmp` has been deprecated since FSL
6.0.6 (at least), and the successor is `eddy`. However, this last
does not provide OpenMP parallelisation capabilities: if a GPU is
available it reduces to `eddy_cuda`; otherwise it reduces to `eddy_cpu`.

Given that GPUs are not freely available within the GHA workflows
infrastructure, executing the cell testing requires a considerable
amount of time (e.g. 1h40min vs 6 min if a GPU is available). However,
this is well below the GHA time limit, and is still reasonable to
execute the cell.

Fixes:
```
CalledProcessError: Command 'b'\n

mkdir -p ../data/ds000221/derivatives/uncorrected_topup_eddy/sub-010006/ses-01/dwi/work\n\n
indx=""\n
for i in `seq 1 67`; do\n
  indx="$indx 1"\n
done\n
echo $indx > ../data/ds000221/derivatives/uncorrected_topup_eddy/sub-010006/ses-01/dwi/work/index.txt\n\n
eddy_openmp \\\n
  --imain=../data/ds000221/sub-010006/ses-01/dwi/sub-010006_ses-01_dwi.nii.gz \\\n
  --mask=../data/ds000221/derivatives/uncorrected/sub-010006/ses-01/dwi/sub-010006_ses-01_brainmask.nii.gz \\\n
  --acqp=../data/ds000221/derivatives/uncorrected_topup/sub-010006/ses-01/dwi/work/pedir.txt \\\n
  --index=../data/ds000221/derivatives/uncorrected_topup_eddy/sub-010006/ses-01/dwi/work/index.txt \\\n
  --bvecs=../data/ds000221/sub-010006/ses-01/dwi/sub-010006_ses-01_dwi.bvec \\\n
  --bvals=../data/ds000221/sub-010006/ses-01/dwi/sub-010006_ses-01_dwi.bval \\\n
  --topup=../data/ds000221/derivatives/uncorrected_topup/sub-010006/ses-01/dwi/work/topup \\\n
  --out=../data/ds000221/derivatives/uncorrected_topup_eddy/sub-010006/ses-01/dwi/dwi \\\n  --repol\n''

returned non-zero exit status 127.
```

raised, for example, in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/5631031363/job/15257597264#step:13:123

Documentation:
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/WhatsNew

Related post in the jisc.mail.ac.uk mailing list:
https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=FSL;566c3c94.2106

Other sources of information:
https://github.com/Washington-University/HCPpipelines/issues/264