BUG: Fix introduction episode non-solution notebook
Fix introduction episode non-solution notebook: use the correct dataset
and subject for the analyses.

Fixes:
```
ValueError: BIDS root does not exist: /home/runner/work/SDC-BIDS-dMRI/SDC-BIDS-dMRI/data/ds000030
```

raised in
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/runs/3025093598?check_suite_focus=true#step:7:44

Synchronize the markdown episode contents and the Jupyter notebooks
(both the non-solution and solution).

Take advantage of the commit to:
- Fix the static image relative path.
- Fix the dataset tree: change the duplicate `fmap` folder for the
missing `func` folder.
- Add the `bids` initial dot extension config statement to avoid the
related warning being displayed.
- Remove the `dipy` and `fury` installation steps: both tools are
assumed to have been installed during setup.
- Use the same DWI volume for to be displayed.
- Fix the output of the bvecs.
- Removed the unexplained `b0` volume slicing block.
- Add exercise to notebooks.
- Fix the suffix syntax in exercise.
- Remove the second exercise: it is already explained/done at the
beginning of the episode.
- Fix typos.
- Remove outputs from non-solution notebook.