ENH: Require Numpy major version smaller than 2
Require Numpy major version smaller than 2: with the recent release of
Numpy 2 a number of dependencies have started to fail, so require Numpy
major versions smaller than 2 until dependencies adapt to Numpy 2.0.

Fixes:
```
AttributeError  Traceback (most recent call last)
AttributeError: _ARRAY_API not found
```

reported for example in:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/runs/9655229240/job/26630796981#step:13:65

Numpy 2.0.0 release notice:
https://numpy.org/news/#numpy-200-released